const $=id=>document.getElementById(id), states=['Новая заявка','Позвонили','Заинтересован','Не дозвонились'];
const labels={school:'Выпускник школы',college:'Выпускник колледжа',university:'Выпускник университета',district:'Участковый инспектор',juvenile:'Ювенальная полиция',patrol:'Патрульная полиция',migration:'Миграционная служба',road_safety:'Дорожная безопасность'};
let db,records=[];
function message(s){$('message').textContent=s}
function cell(row,s){const td=document.createElement('td');td.textContent=s;row.append(td);return td}
function filtered(){const q=$('search').value.trim().toLowerCase();return records.filter(r=>(!$('filter').value||r.call_status===$('filter').value)&&[r.full_name,r.phone,r.city,r.institution,r.direction].join(' ').toLowerCase().includes(q))}
function render(){const list=filtered();$('count').textContent=`Показано: ${list.length}. Всего заявок: ${records.length}`;$('rows').replaceChildren();list.forEach(r=>{const tr=document.createElement('tr');cell(tr,new Date(r.created_at).toLocaleString('ru-RU',{timeZone:'Asia/Almaty'}));const who=cell(tr,r.full_name+' ');const a=document.createElement('a');a.href='tel:'+r.phone;a.textContent=r.phone+' · Позвонить';who.append(document.createElement('br'),a);cell(tr,r.city+' / '+r.institution);cell(tr,labels[r.applicant_status]||r.applicant_status);cell(tr,(labels[r.direction]||r.direction)+' / '+(labels[r.quiz_result]||'Опрос не завершён'));const td=cell(tr,'');const sel=document.createElement('select');states.forEach(s=>{const o=document.createElement('option');o.textContent=s;sel.append(o)});sel.value=r.call_status;const text=document.createElement('textarea');text.value=r.comment;text.maxLength=2000;const save=document.createElement('button');save.textContent='Сохранить';save.onclick=async()=>{save.disabled=true;try{const {data,error}=await db.from('contacts').update({call_status:sel.value,comment:text.value}).eq('id',r.id).select('id');if(error||!data?.length)throw error||new Error();r.call_status=sel.value;r.comment=text.value;message('Сохранено');render()}catch{message('Не удалось сохранить. Проверьте доступ и повторите.')}finally{save.disabled=false}};td.append(sel,text,save);$('rows').append(tr)})}
async function load(){message('Загружаем…');let all=[];try{for(let start=0;;start+=500){const {data,error}=await db.from('contacts').select('*').order('created_at',{ascending:false}).order('id').range(start,start+499);if(error)throw error;all.push(...data);if(data.length<500)break;}records=all;render();message('')}catch{records=[];render();message('Не удалось загрузить заявки. Повторите попытку.')}}
async function check(){const {data:{user},error}=await db.auth.getUser();if(error||!user)return false;const {data,error:denied}=await db.from('contact_admins').select('user_id').eq('user_id',user.id).maybeSingle();if(denied||!data){await db.auth.signOut();message('У этой учётной записи нет доступа к заявкам.');return false;}$('login').hidden=true;$('panel').hidden=false;await load();return true}
$('login').onsubmit=async e=>{e.preventDefault();if(!db)return;const btn=e.submitter;btn.disabled=true;try{const {error}=await db.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});$('password').value='';if(error){message('Не удалось войти. Проверьте e-mail и пароль.');return}await check()}finally{btn.disabled=false}};
$('logout').onclick=async()=>{await db.auth.signOut();records=[];$('rows').replaceChildren();$('panel').hidden=true;$('login').hidden=false;message('')};
$('reload').onclick=load;$('search').oninput=render;$('filter').onchange=render;
$('export').onclick=()=>{const safe=v=>'"'+String(v??'').replace(/^[=+@\-\t\r]/,"'$&").replace(/"/g,'""')+'"';const cols=['created_at','full_name','phone','city','institution','applicant_status','direction','quiz_result','call_status','comment'];const csv='\uFEFF'+[['Дата','ФИО','Телефон','Город','Учебное заведение','Образование','Направление','Результат','Статус','Комментарий'],...filtered().map(r=>cols.map(c=>labels[r[c]]||r[c]))].map(row=>row.map(safe).join(';')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='заявки.csv';a.click();URL.revokeObjectURL(url)};
if(DATABASE_CONFIG.url&&DATABASE_CONFIG.key&&window.supabase){db=supabase.createClient(DATABASE_CONFIG.url,DATABASE_CONFIG.key,{auth:{persistSession:false}});check()}else message('База ещё не подключена. Заполните database-config.js по инструкции.');
